name: Build, Test, and Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub Repository
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sevvyp/plants_v1:latest

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_INSTANCE_IP_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV}}
          script: |
            docker stop plants_v1
            docker rm plants_v1
            docker pull sevvyp/plants_v1:latest
            docker run -d -name plants_v1 -p 80:80 -e AWS_ACCESS_KEY_ID='${{ secrets.DYNAMODB_ACCESS_KEY_ID_DEV }}' -e AWS_SECRET_ACCESS_KEY='${{ secrets.DYNAMODB_SECRET_ACCESS_KEY_DEV }}' -e AWS_DEFAULT_REGION='us-east-2' sevvyp/plants_v1:latest

        